name: Python PEP8

on: [push, pull_request]

jobs:
  PEP8:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v1

    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Lint with pycodestyle
      run: |
        pip install pycodestyle
        pycodestyle *.py --exclude=__init__.py --ignore=E129,E221,E241,E402,E501,W503,W605
        pycodestyle util/*.py --ignore=E129,E221,E241,E251,E402,E501,W503,W605,E731
